#!/usr/bin/env python3
"""Administratum-Agent V1 core logic (sandbox-local, stdlib-only)."""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

AGENT_ROOT = Path(__file__).resolve().parents[1]
NEW_GENERATION_ROOT = AGENT_ROOT.parents[1]
REPO_ROOT = AGENT_ROOT.parents[2]
RUNS_ROOT = NEW_GENERATION_ROOT / "RUNS" / "ADMINISTRATUM_AGENT"
RULES_ROOT = AGENT_ROOT / "brain_node" / "rules"

SKILL_IDS = [
    "build_repo_inventory",
    "classify_repo_zone",
    "build_provenance_index",
    "find_useful_candidates",
    "detect_dirty_runtime_outputs",
    "build_merge_preparation_summary",
    "route_to_organs",
]


@dataclass
class SkillRunResult:
    skill_id: str
    report: Dict[str, Any]
    report_path: str
    receipt: Dict[str, Any]
    receipt_path: str
    run_dir: str


def now_utc() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def stable_id(prefix: str, *parts: str) -> str:
    payload = "|".join(parts).encode("utf-8")
    return f"{prefix}_{hashlib.sha1(payload).hexdigest()[:12]}"


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def read_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: Path, data: Dict[str, Any]) -> None:
    ensure_parent(path)
    with path.open("w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")


def append_jsonl(path: Path, item: Dict[str, Any]) -> None:
    ensure_parent(path)
    with path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(item, ensure_ascii=False) + "\n")


def run_git(args: Sequence[str], cwd: Optional[Path] = None) -> Tuple[int, str]:
    proc = subprocess.run(
        ["git", *args],
        cwd=cwd or REPO_ROOT,
        capture_output=True,
        text=True,
    )
    return proc.returncode, proc.stdout.strip()


def ensure_runs_root() -> None:
    RUNS_ROOT.mkdir(parents=True, exist_ok=True)
    gitignore = RUNS_ROOT / ".gitignore"
    gitkeep = RUNS_ROOT / ".gitkeep"
    if not gitignore.exists():
        gitignore.write_text(
            "\n".join(
                [
                    "# Administratum runtime output (generated by CLI runs)",
                    "RUN-*/",
                    "*.tmp",
                    "!.gitignore",
                    "!.gitkeep",
                    "",
                ]
            ),
            encoding="utf-8",
        )
    if not gitkeep.exists():
        gitkeep.write_text("", encoding="utf-8")


def create_run_dir(out_dir: Optional[str] = None) -> Tuple[str, Path]:
    ensure_runs_root()
    if out_dir:
        out_path = Path(out_dir)
        if not out_path.is_absolute():
            out_path = (REPO_ROOT / out_path).resolve()
    else:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        run_id = f"RUN-ADMINISTRATUM-{stamp}-{stable_id('r', now_utc())[-4:]}"
        out_path = RUNS_ROOT / run_id
    out_path.mkdir(parents=True, exist_ok=True)
    run_id = out_path.name
    (out_path / "receipts").mkdir(parents=True, exist_ok=True)
    return run_id, out_path


def rule_json(name: str) -> Dict[str, Any]:
    return read_json(RULES_ROOT / name)


def normalize_rel_path(path: str, repo_root: Path) -> Tuple[str, bool]:
    raw = Path(path)
    if raw.is_absolute():
        resolved = raw.resolve()
    else:
        resolved = (repo_root / raw).resolve()
    try:
        rel = resolved.relative_to(repo_root.resolve()).as_posix()
        return rel, True
    except ValueError:
        return str(resolved).replace("\\", "/"), False


def classify_zone(rel_path: str, is_inside_repo: bool) -> str:
    rules = rule_json("repo_zone_classification_rules.json")
    if not is_inside_repo:
        if "IMPERIUM_CONTEXT" in rel_path:
            return "LOCAL_PRIVATE"
        return "FORBIDDEN"

    path_norm = rel_path.replace("\\", "/")
    if path_norm.startswith("IMPERIUM_NEW_GENERATION/RUNS/") or path_norm.startswith("IMPERIUM_NEW_GENERATION/RUNTIME/"):
        return "RUNTIME_OUTPUT"

    for row in rules.get("zone_patterns", []):
        zone = row.get("zone")
        for prefix in row.get("prefixes", []):
            if path_norm.startswith(prefix):
                return str(zone)

    if path_norm.startswith("IMPERIUM_NEW_GENERATION/"):
        return "NEW_GENERATION_SANDBOX"
    return "DIRTY_UNKNOWN"


def classify_artifact_type(rel_path: str) -> str:
    p = rel_path.lower()
    ext = Path(rel_path).suffix.lower()
    if ext in {".py", ".ps1", ".sh", ".bat", ".cmd"}:
        return "SCRIPT"
    if "schema" in p and ext == ".json":
        return "SCHEMA"
    if ext == ".json" and "receipt" in p:
        return "RECEIPT_JSON"
    if ext == ".json" and "report" in p:
        return "REPORT_JSON"
    if ext == ".jsonl":
        return "RUNTIME_STATE"
    if ext == ".md" and ("policy" in p or "/policies/" in p):
        return "POLICY_DOC"
    if ext == ".md" and ("doctrine" in p or "doctrinarium" in p):
        return "DOCTRINE_DOC"
    if ext in {".html", ".css", ".js", ".tsx", ".ts"}:
        return "UI_FILE"
    if "advisory_buffer" in p or "design_targets" in p:
        return "ADVISORY_DOC"
    if ext == ".json":
        return "JSON_DATA"
    return "UNKNOWN"


def risk_level(zone_class: str, artifact_type: str, rel_path: str) -> Tuple[str, List[str]]:
    reasons: List[str] = []
    level = "LOW"
    path_norm = rel_path.lower()
    if zone_class in {"FORBIDDEN", "LOCAL_PRIVATE"}:
        level = "HIGH"
        reasons.append("path outside admitted sandbox")
    elif zone_class == "DIRTY_UNKNOWN":
        level = "MEDIUM"
        reasons.append("unclassified or dirty zone")
    if artifact_type == "UNKNOWN":
        level = "MEDIUM" if level == "LOW" else level
        reasons.append("unknown artifact type")
    if "runtime" in path_norm and "imperium_new_generation/runs/" not in path_norm:
        reasons.append("runtime marker outside admitted runtime root")
        level = "HIGH" if level in {"LOW", "MEDIUM"} else level
    return level, reasons


def git_tracked(rel_path: str, repo_root: Path) -> bool:
    rc, _ = run_git(["ls-files", "--error-unmatch", rel_path], cwd=repo_root)
    return rc == 0


def classify_path(path: str, repo_root: Path, tracked_hint: Optional[bool] = None) -> Dict[str, Any]:
    rel, inside = normalize_rel_path(path, repo_root)
    zone = classify_zone(rel, inside)
    art = classify_artifact_type(rel)
    risk, reasons = risk_level(zone, art, rel)
    if not inside:
        tracked = False
    elif tracked_hint is None:
        tracked = git_tracked(rel, repo_root)
    else:
        tracked = tracked_hint
    provenance_status = "KNOWN_COMMITTED" if tracked else "UNKNOWN_UNTRACKED"
    trust_level = "SANDBOX_TRUSTED_IF_CLEAN" if zone == "NEW_GENERATION_SANDBOX" and tracked else "UNKNOWN"
    if zone == "RUNTIME_OUTPUT":
        trust_level = "RUNTIME_NOT_CANON"
    if zone in {"FORBIDDEN", "LOCAL_PRIVATE"}:
        trust_level = "OUTSIDE_SCOPE"

    return {
        "artifact_id": stable_id("artifact", rel),
        "path": rel,
        "zone_class": zone,
        "artifact_type": art,
        "provenance_status": provenance_status,
        "trust_level": trust_level,
        "risk_level": risk,
        "risk_reasons": reasons,
        "git_tracked": tracked,
    }


def route_for_object(obj: Dict[str, Any]) -> List[str]:
    zone = obj.get("zone_class", "UNKNOWN")
    art = obj.get("artifact_type", "UNKNOWN")
    risk = obj.get("risk_level", "LOW")
    routes: List[str] = []
    if risk == "HIGH":
        routes.extend(["CUSTODES_AGENT", "INQUISITION_AGENT"])
    if art == "SCRIPT":
        routes.append("MECHANICUS_AGENT")
    if art in {"POLICY_DOC", "DOCTRINE_DOC"}:
        routes.append("DOCTRINARIUM_AGENT")
    if zone == "ADVISORY":
        routes.append("ASTRONOMICON_AGENT")
    if zone in {"FORBIDDEN", "LOCAL_PRIVATE"}:
        routes.append("THRONE_AGENT")
    if not routes:
        routes.append("MECHANICUS_AGENT")
    ordered: List[str] = []
    seen = set()
    for r in routes:
        if r not in seen:
            ordered.append(r)
            seen.add(r)
    return ordered


def build_inventory(repo_root: Path, run_id: str, run_dir: Path, max_objects_preview: int = 250) -> SkillRunResult:
    objects_jsonl = run_dir / "inventory_objects.jsonl"
    if objects_jsonl.exists():
        objects_jsonl.unlink()

    rc, tracked_out = run_git(["ls-files"], cwd=repo_root)
    tracked_set = set(tracked_out.splitlines()) if rc == 0 else set()

    zone_counts: Counter[str] = Counter()
    artifact_counts: Counter[str] = Counter()
    top_level_dirs: Counter[str] = Counter()
    objects_preview: List[Dict[str, Any]] = []
    total_files = 0

    skip_dirs = {".git", "__pycache__", "node_modules", ".venv", "venv"}
    for root, dirs, files in os.walk(repo_root):
        dirs[:] = [d for d in dirs if d not in skip_dirs]
        for name in files:
            total_files += 1
            abs_path = Path(root) / name
            rel = abs_path.resolve().relative_to(repo_root.resolve()).as_posix()
            obj = classify_path(rel, repo_root, tracked_hint=(rel in tracked_set))
            obj["recommended_next_route"] = route_for_object(obj)
            zone_counts[obj["zone_class"]] += 1
            artifact_counts[obj["artifact_type"]] += 1
            top = rel.split("/", 1)[0]
            top_level_dirs[top] += 1
            append_jsonl(objects_jsonl, obj)
            if len(objects_preview) < max_objects_preview:
                objects_preview.append(obj)

    warnings: List[str] = []
    if total_files > max_objects_preview:
        warnings.append("objects preview truncated; full inventory is in inventory_objects.jsonl")

    unknown_count = zone_counts.get("DIRTY_UNKNOWN", 0) + zone_counts.get("FORBIDDEN", 0)
    verdict = "PASS_WITH_WARNINGS" if warnings or unknown_count > 0 else "PASS"

    report = {
        "report_type": "REPO_INVENTORY_REPORT",
        "agent_id": "ADMINISTRATUM_AGENT",
        "run_id": run_id,
        "repo_root": str(repo_root),
        "git_head": get_head(repo_root),
        "generated_at_utc": now_utc(),
        "total_files": total_files,
        "zone_counts": dict(zone_counts),
        "artifact_counts": dict(artifact_counts),
        "top_level_dirs": dict(top_level_dirs),
        "objects_preview": objects_preview,
        "objects_jsonl_path": str(objects_jsonl),
        "warnings": warnings,
        "verdict": verdict,
    }

    report_path = run_dir / "inventory_report.json"
    write_json(report_path, report)
    receipt = skill_receipt(
        run_id=run_id,
        skill_id="build_repo_inventory",
        input_refs=[str(repo_root)],
        outputs=[str(report_path), str(objects_jsonl)],
        verdict=verdict,
        warnings=warnings,
    )
    receipt_path = write_skill_receipt(run_dir, "build_repo_inventory", receipt)
    return SkillRunResult(
        skill_id="build_repo_inventory",
        report=report,
        report_path=str(report_path),
        receipt=receipt,
        receipt_path=str(receipt_path),
        run_dir=str(run_dir),
    )


def get_head(repo_root: Path) -> str:
    _, out = run_git(["rev-parse", "HEAD"], cwd=repo_root)
    return out


def get_last_commit(path: str, repo_root: Path) -> Dict[str, Optional[str]]:
    rc, out = run_git(["log", "-1", "--format=%H|%aI", "--", path], cwd=repo_root)
    if rc != 0 or not out:
        return {"last_commit": None, "last_commit_at": None}
    parts = out.split("|", 1)
    return {"last_commit": parts[0], "last_commit_at": parts[1] if len(parts) > 1 else None}


def get_first_seen(path: str, repo_root: Path) -> Dict[str, Optional[str]]:
    rc, out = run_git(["log", "--diff-filter=A", "--format=%H|%aI", "--", path], cwd=repo_root)
    if rc != 0 or not out:
        return {"first_seen_commit": None, "first_seen_at": None}
    line = out.splitlines()[-1]
    parts = line.split("|", 1)
    return {"first_seen_commit": parts[0], "first_seen_at": parts[1] if len(parts) > 1 else None}


def iter_inventory_objects(inventory_report_path: Path) -> Iterable[Dict[str, Any]]:
    report = read_json(inventory_report_path)
    raw_jsonl = str(report.get("objects_jsonl_path", "")).strip()
    jsonl_path = Path(raw_jsonl) if raw_jsonl else None
    if jsonl_path is not None and not jsonl_path.is_absolute():
        jsonl_path = (inventory_report_path.parent / jsonl_path).resolve()
    if jsonl_path is not None and jsonl_path.exists() and jsonl_path.is_file():
        for line in jsonl_path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                yield json.loads(line)
        return
    for item in report.get("objects_preview", []):
        yield item


def build_provenance_index(repo_root: Path, run_id: str, run_dir: Path, inventory_report_path: Path, limit: int = 400) -> SkillRunResult:
    entries: List[Dict[str, Any]] = []
    warnings: List[str] = []

    for idx, obj in enumerate(iter_inventory_objects(inventory_report_path)):
        if idx >= limit:
            warnings.append(f"provenance index limited to first {limit} objects")
            break
        path = str(obj.get("path", ""))
        tracked = bool(obj.get("git_tracked", False))
        last_commit = get_last_commit(path, repo_root) if tracked else {"last_commit": None, "last_commit_at": None}
        first_seen = get_first_seen(path, repo_root) if tracked else {"first_seen_commit": None, "first_seen_at": None}
        entry = {
            "path": path,
            "git_tracked": tracked,
            "git_head_seen": get_head(repo_root),
            "source_type": "commit" if tracked else ("runtime" if "RUNS/" in path or "RUNTIME/" in path else "unknown"),
            "source_id": last_commit["last_commit"] if tracked else None,
            "first_seen": first_seen["first_seen_at"],
            "created_by": "unknown",
            "verified_by": "git",
            "trust_status": obj.get("trust_level", "UNKNOWN"),
            "last_classification": {
                "zone_class": obj.get("zone_class"),
                "artifact_type": obj.get("artifact_type"),
                "risk_level": obj.get("risk_level"),
            },
            "last_commit": last_commit["last_commit"],
            "last_commit_at": last_commit["last_commit_at"],
            "first_seen_commit": first_seen["first_seen_commit"],
        }
        entries.append(entry)

    report = {
        "report_type": "PROVENANCE_INDEX_REPORT",
        "agent_id": "ADMINISTRATUM_AGENT",
        "run_id": run_id,
        "generated_at_utc": now_utc(),
        "inventory_report_path": str(inventory_report_path),
        "entry_count": len(entries),
        "entries": entries,
        "warnings": warnings,
        "verdict": "PASS_WITH_WARNINGS" if warnings else "PASS",
    }
    report_path = run_dir / "provenance_report.json"
    write_json(report_path, report)
    receipt = skill_receipt(
        run_id=run_id,
        skill_id="build_provenance_index",
        input_refs=[str(inventory_report_path)],
        outputs=[str(report_path)],
        verdict=report["verdict"],
        warnings=warnings,
    )
    receipt_path = write_skill_receipt(run_dir, "build_provenance_index", receipt)
    return SkillRunResult(
        skill_id="build_provenance_index",
        report=report,
        report_path=str(report_path),
        receipt=receipt,
        receipt_path=str(receipt_path),
        run_dir=str(run_dir),
    )


def find_useful_candidates(run_id: str, run_dir: Path, inventory_report_path: Path) -> SkillRunResult:
    scripts: List[Dict[str, Any]] = []
    gates: List[Dict[str, Any]] = []
    policies: List[Dict[str, Any]] = []
    dashboards: List[Dict[str, Any]] = []
    memories: List[Dict[str, Any]] = []

    for obj in iter_inventory_objects(inventory_report_path):
        path = str(obj.get("path", ""))
        lower = path.lower()
        if obj.get("artifact_type") == "SCRIPT" and obj.get("zone_class") in {"CANON_CORE", "NEW_GENERATION_SANDBOX"}:
            scripts.append({"path": path, "risk_level": obj.get("risk_level"), "route": route_for_object(obj)})
        if "/gates/" in lower or "gate_" in lower:
            gates.append({"path": path, "risk_level": obj.get("risk_level"), "route": route_for_object(obj)})
        if "/policies/" in lower or "policy" in lower:
            policies.append({"path": path, "risk_level": obj.get("risk_level"), "route": route_for_object(obj)})
        if "sanctum" in lower or "control_center" in lower:
            dashboards.append({"path": path, "risk_level": obj.get("risk_level"), "route": route_for_object(obj)})
        if "/memory/" in lower:
            memories.append({"path": path, "risk_level": obj.get("risk_level"), "route": route_for_object(obj)})

    report = {
        "report_type": "USEFUL_CANDIDATES_REPORT",
        "agent_id": "ADMINISTRATUM_AGENT",
        "run_id": run_id,
        "generated_at_utc": now_utc(),
        "inventory_report_path": str(inventory_report_path),
        "script_candidates": scripts[:120],
        "gate_candidates": gates[:120],
        "policy_candidates": policies[:120],
        "dashboard_candidates": dashboards[:120],
        "memory_candidates": memories[:120],
        "counts": {
            "script_candidates": len(scripts),
            "gate_candidates": len(gates),
            "policy_candidates": len(policies),
            "dashboard_candidates": len(dashboards),
            "memory_candidates": len(memories),
        },
        "requires_mechanicus_review": len(scripts) > 0,
        "requires_inquisition_review": any(x.get("risk_level") == "HIGH" for x in scripts + gates + policies),
        "requires_owner_decision": any("THRONE_AGENT" in x.get("route", []) for x in scripts + gates + policies),
        "verdict": "PASS",
    }
    report_path = run_dir / "useful_candidates_report.json"
    write_json(report_path, report)
    receipt = skill_receipt(
        run_id=run_id,
        skill_id="find_useful_candidates",
        input_refs=[str(inventory_report_path)],
        outputs=[str(report_path)],
        verdict="PASS",
        warnings=[],
    )
    receipt_path = write_skill_receipt(run_dir, "find_useful_candidates", receipt)
    return SkillRunResult(
        skill_id="find_useful_candidates",
        report=report,
        report_path=str(report_path),
        receipt=receipt,
        receipt_path=str(receipt_path),
        run_dir=str(run_dir),
    )


def detect_dirty_runtime_outputs(repo_root: Path, run_id: str, run_dir: Path) -> SkillRunResult:
    rules = rule_json("dirt_detection_rules.json")
    dirty_patterns = [p.replace("\\", "/") for p in rules.get("dirty_patterns", [])]
    allowed_runtime = [p.replace("\\", "/") for p in rules.get("allowed_runtime_roots", [])]

    rc, tracked_out = run_git(["ls-files"], cwd=repo_root)
    tracked_paths = tracked_out.splitlines() if rc == 0 else []

    tracked_runtime_paths: List[str] = []
    for p in tracked_paths:
        norm = p.replace("\\", "/")
        if any(norm.startswith(ap) for ap in allowed_runtime):
            continue
        if any(norm.startswith(dp) for dp in dirty_patterns):
            tracked_runtime_paths.append(norm)

    rc, status_out = run_git(["status", "--porcelain"], cwd=repo_root)
    status_paths: List[str] = []
    if rc == 0:
        for line in status_out.splitlines():
            if len(line) > 3:
                status_paths.append(line[3:].replace("\\", "/"))

    modified_runtime_paths = [
        p
        for p in status_paths
        if any(marker in p for marker in ["RUNS/", "RUNTIME/", "state_delta", "checkpoint"])
        and not any(p.startswith(ap) for ap in allowed_runtime)
        and not p.endswith("/.gitignore")
        and not p.endswith("/.gitkeep")
        and p not in {"IMPERIUM_NEW_GENERATION/RUNS/", "IMPERIUM_NEW_GENERATION/RUNS/ADMINISTRATUM_AGENT/"}
    ]
    dirty = bool(tracked_runtime_paths or modified_runtime_paths)
    warnings: List[str] = []
    if tracked_runtime_paths:
        warnings.append("tracked runtime-pattern paths detected outside admitted runtime roots")
    if modified_runtime_paths:
        warnings.append("modified runtime-like paths detected in working tree")

    report = {
        "report_type": "DIRTY_RUNTIME_REPORT",
        "agent_id": "ADMINISTRATUM_AGENT",
        "run_id": run_id,
        "generated_at_utc": now_utc(),
        "dirty_runtime_detected": dirty,
        "tracked_runtime_paths": tracked_runtime_paths,
        "modified_runtime_paths": modified_runtime_paths,
        "recommended_action": (
            "Route runtime outputs to IMPERIUM_NEW_GENERATION/RUNS/ADMINISTRATUM_AGENT and keep tracked architecture static."
            if dirty
            else "No runtime pollution detected by current rules."
        ),
        "architectural_fix": "RUNS_LAYER_ONLY",
        "warnings": warnings,
        "verdict": "PASS_WITH_WARNINGS" if dirty else "PASS",
    }
    report_path = run_dir / "dirty_runtime_report.json"
    write_json(report_path, report)
    receipt = skill_receipt(
        run_id=run_id,
        skill_id="detect_dirty_runtime_outputs",
        input_refs=[str(repo_root)],
        outputs=[str(report_path)],
        verdict=report["verdict"],
        warnings=warnings,
    )
    receipt_path = write_skill_receipt(run_dir, "detect_dirty_runtime_outputs", receipt)
    return SkillRunResult(
        skill_id="detect_dirty_runtime_outputs",
        report=report,
        report_path=str(report_path),
        receipt=receipt,
        receipt_path=str(receipt_path),
        run_dir=str(run_dir),
    )


def route_to_organs(run_id: str, run_dir: Path, findings: List[Dict[str, Any]], requested_action: str = "") -> SkillRunResult:
    rejection = rule_json("artifact_rejection_rules.json")
    lower_action = requested_action.lower()
    if lower_action and any(k in lower_action for k in rejection.get("mutation_keywords", [])):
        report = {
            "report_type": "ROUTING_RECOMMENDATIONS_REPORT",
            "agent_id": "ADMINISTRATUM_AGENT",
            "run_id": run_id,
            "generated_at_utc": now_utc(),
            "requested_action": requested_action,
            "verdict": "REJECT_MUTATION_REQUEST",
            "routes": [
                {
                    "reason": "mutation keyword detected",
                    "route_to": ["CUSTODES_AGENT", "THRONE_AGENT"],
                }
            ],
            "warnings": ["direct deletion/merge request rejected by mutation policy"],
        }
    else:
        routes: List[Dict[str, Any]] = []
        for item in findings:
            cls = classify_path(str(item.get("path", "")), REPO_ROOT)
            routes.append(
                {
                    "path": cls["path"],
                    "zone_class": cls["zone_class"],
                    "artifact_type": cls["artifact_type"],
                    "risk_level": cls["risk_level"],
                    "route_to": route_for_object(cls),
                }
            )
        report = {
            "report_type": "ROUTING_RECOMMENDATIONS_REPORT",
            "agent_id": "ADMINISTRATUM_AGENT",
            "run_id": run_id,
            "generated_at_utc": now_utc(),
            "requested_action": requested_action,
            "verdict": "PASS",
            "routes": routes,
            "warnings": [],
        }

    report_path = run_dir / "routing_recommendations_report.json"
    write_json(report_path, report)
    receipt = skill_receipt(
        run_id=run_id,
        skill_id="route_to_organs",
        input_refs=[requested_action or "findings_inline"],
        outputs=[str(report_path)],
        verdict=report["verdict"],
        warnings=report.get("warnings", []),
    )
    receipt_path = write_skill_receipt(run_dir, "route_to_organs", receipt)
    return SkillRunResult(
        skill_id="route_to_organs",
        report=report,
        report_path=str(report_path),
        receipt=receipt,
        receipt_path=str(receipt_path),
        run_dir=str(run_dir),
    )


def build_merge_preparation_summary(
    run_id: str,
    run_dir: Path,
    inventory_report: Dict[str, Any],
    provenance_report: Dict[str, Any],
    candidates_report: Dict[str, Any],
    dirty_runtime_report: Dict[str, Any],
    routing_report: Dict[str, Any],
) -> SkillRunResult:
    warnings: List[str] = []
    if dirty_runtime_report.get("dirty_runtime_detected"):
        warnings.append("runtime pollution detected in repository scope")

    summary = {
        "report_type": "MERGE_PREPARATION_SUMMARY",
        "agent_id": "ADMINISTRATUM_AGENT",
        "run_id": run_id,
        "generated_at_utc": now_utc(),
        "zone_map": inventory_report.get("zone_counts", {}),
        "artifact_map": inventory_report.get("artifact_counts", {}),
        "provenance_entries": provenance_report.get("entry_count", 0),
        "candidate_counts": candidates_report.get("counts", {}),
        "dirty_runtime_detected": dirty_runtime_report.get("dirty_runtime_detected", False),
        "dirty_runtime_paths_sample": dirty_runtime_report.get("tracked_runtime_paths", [])[:20],
        "routing_preview": routing_report.get("routes", [])[:20],
        "top_risks": [
            "No direct canon mutation by Administratum-Agent.",
            "Runtime outputs must remain in RUNS layer.",
            "High-risk or forbidden scope items require Custodes/Owner route.",
        ],
        "recommended_next_actions": [
            "Use Custodes and Inquisition review for HIGH/FORBIDDEN findings.",
            "Use Mechanicus review for script/tool candidates.",
            "Use Doctrinarium review for policy/doctrine candidates.",
            "Keep this report advisory until Servitor implementation and Owner gate.",
        ],
        "verdict": "PASS_WITH_WARNINGS" if warnings else "PASS",
        "warnings": warnings,
    }

    summary_path = run_dir / "merge_preparation_summary.json"
    write_json(summary_path, summary)
    md_path = run_dir / "merge_preparation_summary.md"
    md_path.write_text(
        "\n".join(
            [
                "# Administratum Merge Preparation Summary",
                "",
                f"- run_id: {run_id}",
                f"- verdict: {summary['verdict']}",
                f"- dirty_runtime_detected: {str(summary['dirty_runtime_detected']).lower()}",
                f"- provenance_entries: {summary['provenance_entries']}",
                "",
                "## Recommended Next Actions",
                *[f"- {line}" for line in summary["recommended_next_actions"]],
                "",
            ]
        ),
        encoding="utf-8",
    )

    receipt = skill_receipt(
        run_id=run_id,
        skill_id="build_merge_preparation_summary",
        input_refs=[
            "inventory_report",
            "provenance_report",
            "candidates_report",
            "dirty_runtime_report",
            "routing_report",
        ],
        outputs=[str(summary_path), str(md_path)],
        verdict=summary["verdict"],
        warnings=warnings,
    )
    receipt_path = write_skill_receipt(run_dir, "build_merge_preparation_summary", receipt)
    return SkillRunResult(
        skill_id="build_merge_preparation_summary",
        report=summary,
        report_path=str(summary_path),
        receipt=receipt,
        receipt_path=str(receipt_path),
        run_dir=str(run_dir),
    )


def skill_receipt(
    run_id: str,
    skill_id: str,
    input_refs: List[str],
    outputs: List[str],
    verdict: str,
    warnings: List[str],
) -> Dict[str, Any]:
    return {
        "receipt_type": "ADMINISTRATUM_SKILL_RUN_RECEIPT",
        "agent_id": "ADMINISTRATUM_AGENT",
        "run_id": run_id,
        "skill_id": skill_id,
        "input_refs": input_refs,
        "outputs": outputs,
        "verdict": verdict,
        "warnings": warnings,
        "mutated_canon": False,
        "deleted_files": False,
        "timestamp": now_utc(),
    }


def write_skill_receipt(run_dir: Path, skill_id: str, receipt: Dict[str, Any]) -> Path:
    path = run_dir / "receipts" / f"{skill_id}_receipt.json"
    write_json(path, receipt)
    return path


def record_run_event(run_dir: Path, event_type: str, payload: Dict[str, Any]) -> None:
    event = {
        "event_id": stable_id("evt", event_type, now_utc()),
        "event_type": event_type,
        "timestamp_utc": now_utc(),
        "agent": "ADMINISTRATUM_AGENT",
        "payload": payload,
    }
    append_jsonl(run_dir / "events.jsonl", event)


def load_manifest() -> Dict[str, Any]:
    return read_json(AGENT_ROOT / "agent_manifest.json")


def status_snapshot() -> Dict[str, Any]:
    manifest = load_manifest()
    return {
        "agent_id": manifest.get("agent_id", "ADMINISTRATUM_AGENT"),
        "agent_name": manifest.get("agent_name", "Administratum-Agent"),
        "version": manifest.get("version", "UNKNOWN"),
        "status": manifest.get("status", "UNKNOWN"),
        "runtime_policy": manifest.get("runtime_mode", "UNKNOWN"),
        "supported_skills": manifest.get("supported_skills", []),
        "repo_root": str(REPO_ROOT),
        "new_generation_root": str(NEW_GENERATION_ROOT),
        "runs_root": str(RUNS_ROOT),
        "git_head": get_head(REPO_ROOT),
        "timestamp_utc": now_utc(),
    }
